#########################################
# General Settings
#########################################

# Automatically set window title
set-window-option -g automatic-rename on
set-option -g set-titles on

# Support for undercurls
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

set -g status-keys vi
set -g history-limit 10000

setw -g mode-keys vi
setw -g monitor-activity on
set -g mouse on

set -g detach-on-destroy off  # don't exit from tmux when closing a session
set -sg escape-time 0  # faster key response

#########################################
# Key Bindinigs
#########################################

# Vim style resizing
bind-key J resize-pane -D 5
bind-key K resize-pane -U 5
bind-key H resize-pane -L 5
bind-key L resize-pane -R 5

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Use Alt-vim keys without prefix key to switch panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Reload tmux config
bind r source-file ~/.config/tmux/tmux.conf

# TSM
bind-key -r i run-shell "tmux neww ~/.local/bin/tsm"

# Send prefix key to <CTRL>+<SPACE>
set-option -g prefix C-space
set-option -g prefix2 C-b

#########################################
# Theme
#########################################

white='#f8f8f2'
gray='#44475a'
dark_gray='#282a36'
light_purple='#bd93f9'
dark_purple='#6272a4'
cyan='#8be9fd'
green='#50fa7b'
orange='#ffb86c'
red='#ff5555'
pink='#ff79c6'
yellow='#f1fa8c'

bg_color=${gray}

set -g pane-active-border-style "fg=${light_purple}"
set -g pane-border-style "fg=${gray}"
set -g message-style "bg=${gray},fg=${white}"
set -g status-style "bg=${bg_color},fg=${white}"
set -g status-left "#[bg=${green},fg=${dark_gray}]#{?client_prefix,#[bg=${yellow}],} #S "

setw -g window-status-current-format "#[fg=${white},bg=${dark_purple}] #I #W "
setw -g window-status-format "#[fg=${white}]#[bg=${bg_color}] #I #W"
setw -g window-status-activity-style "bold"
setw -g window-status-bell-style "bold"


